version: '3.8'

services:
  nextjs-app:
    container_name: nextjs_local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Pass this so the build step (Static Generation) can see the URL
        NEXT_PUBLIC_SUPABASE_URL: http://host.docker.internal:54321
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      # Runtime override
      NEXT_PUBLIC_SUPABASE_URL: http://host.docker.internal:54321
    extra_hosts:
      - "host.docker.internal:host-gateway"

